### ISSUE TITLE
Update error message when file is not found in S3

### ISSUE THREAD

**Issue by punkstar** [meanbee/magedbm#26]
Currently reads `File such file found in S3 bucket.`, should read `No such file found in S3 bucket.`.

Can be found in [Meanbee\Magedbm\Command\GetCommand::downloadBackup](https://github.com/meanbee/magedbm/blob/31e46b2d3e3d75788bff89c1f4cd46f9fd3d9fd6/src/Meanbee/Magedbm/Command/GetCommand.php).

**Comment by bobbyshaw** [comment]
Man, you could have a PR'd that from within github as quickly ;)
