### ISSUE TITLE
Triggers in enterprise cause tables to be read only

### ISSUE THREAD

**Issue by brideo** [meanbee/magedbm#28]
Because the trigger is created by a certain user on the production/downloaded environment, we can not edit that table on our local environment unless we have that user.

n98 Magerun get around this issue by stripping out this command on export:

`mysqldump --single-transaction --quick -h'localhost' -u'db_user' -p'db_password' 'db_name' | sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' > 'export_name.sql';`

**Comment by tgerulaitis** [comment]
Good catch! This explains why we didn't encounter this issue until we started using magedbm.
