### ISSUE TITLE
Only clean up tmp file if rename was successful

### ISSUE THREAD

**Issue by punkstar** [meanbee/magedbm#30]
There already seems to be a check for this in checking the return type for `rename` ([Meanbee\Magedbm\Command\GetCommand::backupMove](https://github.com/meanbee/magedbm/blob/31e46b2d3e3d75788bff89c1f4cd46f9fd3d9fd6/src/Meanbee/Magedbm/Command/GetCommand.php#L221)) but I've seen a warning emitted and `rename` returning true when using [meanbee/docker-magento-tools](https://github.com/meanbee/docker-magento-tools).

The fix would be to perform `is_writable` check on `$newFilename` directory first.

**Comment by bobbyshaw** [comment]
How about a `file_exists` check after the rename has been done for a more confident check? Or both, if I want to be really verbose with exceptions thrown.

**Comment by bobbyshaw** [comment]
I've added a PR for this but it would be good to know what the warning was as I haven't been able to reproduce by removing permissions.  As I don't actually clean up the tmp directory in this branch of code so I'm not sure where your file would have gone.
