### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by punkstar** [meanbee/magedbm#39]
We need to make a release to include:
- #35 
- #37

There are some commits on master and some on develop, so need to be careful with that!

**Comment by bobbyshaw** [comment]
Merged master into develop. Waiting for one more PR to be approved and will create release.

**Comment by bobbyshaw** [comment]
Merged master into develop. Waiting for one more PR to be approved and will create release.

**Comment by bobbyshaw** [comment]
1.5.0 now available. Please run `magedbm.phar self-update`
