### ISSUE TITLE
Support --routine

### ISSUE THREAD

**Issue by adam-paterson** [meanbee/magedbm#40]
Magento has stored routines for partial indexing. We need to add support for the ```--routine``` flag with n98-magerun. See https://github.com/netz98/n98-magerun/issues/529

**Comment by bobbyshaw** [comment]
DB dump is done with https://github.com/ifsnop/mysqldump-php. Quick look suggests that this supports routine so the flag should be added and passed through to that.

**Comment by bobbyshaw** [comment]
Hey @adam-paterson, I'm looking to do a little work on magedbm to do a minor release. I'm happy to look into this one but didn't want to start while you're self-assigned. Are you happy for me to work on this?

**Comment by adam-paterson** [comment]
@bobbyshaw Yeah feel free, I'm going to look into #38
