### ISSUE TITLE
Error during import on mysql 5.7

### ISSUE THREAD

**Issue by jahvi** [meanbee/magedbm#42]
When I try to run the `get` command on a site running mysql 5.7 I get the following error:

    Importing SQL dump /tmp/magedbm/db-2017-01-16_171501.sql.gz to database db
    gzip: error writing to output: Broken pipe
    mysql: [ERROR] unknown variable 'pass=root'

It seems to be related to [this issue](https://github.com/netz98/n98-magerun/issues/732) on magerun which was fixed. If I run it with the `--download-only` flag and then `n98-magerun db:import db-2017-01-16_171501.sql.gz --compression=gzip` it does work.

Is it possible that the phar was packaged with an older version of magerun that doesn't include the fix? I tried running the `box build` command on a fresh copy of the master branch and still got the same error though so it might be something else.

**Comment by bobbyshaw** [comment]
Thanks for the report @jahvi. It seems we would need to update the dependences with compose update before creating a new phar.  There are a few other items on our list now so I'll look into this as part of a new release.

**Comment by jahvi** [comment]
Thanks, is there any reason why not to allow magedbm to be installed globally with composer and use the `bin/magedbm` executable instead of using a phar? It'd make handling dependencies and updating easier, I had to make [a few tweaks](https://github.com/meanbee/magedbm/compare/master...jahvi:master) on my fork to allow for this but it works well (except the put command not working but I haven't looked into it yet).

**Comment by bobbyshaw** [comment]
I haven't looked into that use case. We chose the phar route internally so we can install on production boxes with no concern for dependency management or conflicts. If we can find a way for it to support both then that would be fine.

**Comment by jahvi** [comment]
It should work the same way in theory, the only issue I found after installing globally was trying to run the `put` command:

    Fatal error: Call to a member function getDetectSubFolders() on null in /var/www/magedbm/vendor/n98/magerun/src/N98/Magento/Application.php on line 221

I think it's having trouble getting the Magento root but not sure why, commenting [these lines](https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Application.php#L220-L222) in magerun's Application.php file seem to fix the issue. I can open a different issue to keep track of it, installing it globally works for me so I don't mind having a look.

**Comment by jahvi** [comment]
Just for reference I managed to 'fix' the error above by specifying magerun 1.97.22 in the composer.json file, looks like they changed the [way they detect magento](https://github.com/netz98/n98-magerun/compare/1.97.22...1.97.23#diff-e42fe36d3628b1f8e91a653d64c7ba6dR221) on 1.97.23 and it was throwing the error above, it might be possible to update the code to use the latest version of magerun but this seems like a decent workaround while also providing support for mysql 5.7.

I can send a PR with my changes that provide support to run magedbm a global install and the mysql 5.7 if you guys want, closing this for now.
