### ISSUE TITLE
Call to a member function getDetectSubFolders() on a non-object

### ISSUE THREAD

**Issue by PushEngineering** [meanbee/magedbm#52]
running `magedbm put` is throwing this:

```
ubuntu@application2:/var/www/html/magento/current$ magedbm.phar put --history-count="10" --bucket="magedbm-push" push
PHP Fatal error:  Call to a member function getDetectSubFolders() on a non-object in phar:///usr/local/bin/magedbm.phar/vendor/n98/magerun/src/N98/Magento/Application.php on line 221
```

Im running it from the root of the magento install...

any ideas?

**Comment by bobbyshaw** [comment]
Hi @PushEngineering. Looks like this bug came in after updating some of the dependencies. I've reworked our code to be compatible with these changes and release v1.5.1 that resolves this error.

Please run `magedbm.phar --self-update` and try again.

**Comment by PushEngineering** [comment]
@bobbyshaw Thanks for that seems to have got it. On the new SDITH platform we are using this and mageconfig to help our tooling.

**Comment by bobbyshaw** [comment]
👍
