### ISSUE TITLE
Strip option not working properly

### ISSUE THREAD

**Issue by davidselo** [meanbee/magedbm#57]
Good afternoon, 

First of all thanks for sharing this tool to the community, it is very helpful for speeding up the process of getting databases backups. 

I am testing the tool and I got the next issue when I try to strip some tables from the backup. 
For example, when I try the command  magedbm put --strip="@trade @stripped @search @newsletter @emails" local

It comes up with the next issue: 

[Symfony\Component\Console\Exception\RuntimeException]    
  Too many arguments, expected arguments "command" "name".  

I would be great if you could have a look at the issue. 

Have a nice day, 
David

**Comment by brideo** [comment]
https://github.com/meanbee/magedbm/blob/master/src/Meanbee/Magedbm/Command/GetCommand.php#L196

It looks like you could add a parameter here if you have time to submit a PR?

**Comment by punkstar** [comment]
@davidselo Can you provide your full command for running `magedbm` please? This should work fine.

**Comment by davidselo** [comment]
Hello @punkstar,

Thanks for your quick answer. 

That is the one the works:

`magedbm put --strip="@trade" local
`

That's the one that doesn't: 

`magedbm put --strip="@trade @stripped @search @newsletter @emails" local`

I added the magebdm the same way you did in https://github.com/meanbee/docker-magento-tools with a Dockerfile and adding the script the same way you did

```
#!/bin/bash

/magedbm.phar configure --key="$AWS_ACCESS_KEY_ID" --secret="$AWS_SECRET_ACCESS_KEY" --region="$AWS_REGION" --bucket="$AWS_BUCKET"
cd $MAGE_ROOT_DIR && /magedbm.phar $@
```

I had to create a new container rather than use the [docker-magento-tools](https://github.com/meanbee/docker-magento-tools) because I tested with the web server container we use and it didn't work. because of the way we have created the container. 

Also, I am running the command into the container with the next command: 

`docker-compose exec webserver magedbm put --strip="@trade @stripped @search @newsletter @emails" local`

I hope it's more clear now.

**Comment by davidselo** [comment]
Hello again, 

it looks like is an issue with the way the bash/script handle the parameters data. 

I tested the command manually and it works, so it is nothing related with the magedbm.phar, I apologize for the inconvenience. 

Thanks for your help.

**Comment by davidselo** [comment]
I leave here my solution just in case someone else has the same problem with this

```
#!/bin/bash

/magedbm.phar configure --key="$AWS_ACCESS_KEY_ID" --secret="$AWS_SECRET_ACCESS_KEY" --region="$AWS_REGION" --bucket="$AWS_BUCKET"
cd $MAGE_ROOT_DIR && /magedbm.phar "$@"
```
The only difference is the "$@" with quotes

**Comment by bobbyshaw** [comment]
Glad you found the issue, and thanks for leaving the solution @davidselo!
