### ISSUE TITLE
Fatal Error: Cannot redeclare class

### ISSUE THREAD

**Issue by bobbyshaw** [meanbee/magedbm#8]
```
PHP Fatal error:  include(): Cannot redeclare class n98\magento\command\system\store\config\baseurllistcommand in phar:///chroot/home/penheave/magedbm.phar/vendor/composer/ClassLoader.php on line 412
Segmentation fault
```

Using the put command on php 5.3.24

**Comment by bobbyshaw** [comment]
Likely related: https://github.com/netz98/n98-magerun/issues/224

**Comment by punkstar** [comment]
I've experienced the problem on that machine with that client using magerun before.  The fix is to use `apc.enable_cli=0` as the ticket suggests.

**Comment by bobbyshaw** [comment]
Yeah, I hadn't read the issue in full, I was making a note for later :)
